### ISSUE TITLE
任务清单

### ISSUE THREAD

**Issue by yeluoqiuzhi** [yeluoqiuzhi/FancyFighter#4]
# 任务清单

1. 画第二关(当前)的另一部分，同样的图集。
2. 封装一个血量条，提供接口给所有活物使用。
3. 封装一个爆炸特效，供所有东西爆炸后使用。
4. 道具:血瓶

我先做2号

**Comment by yeluoqiuzhi** [comment]
2号占有

**Comment by KuoRave** [comment]
我是3号哦,么么哒

**Comment by yeluoqiuzhi** [comment]
血量条完成，接下来我去弄一个道具的基类，之前各自继承他，写道具

**Comment by KuoRave** [comment]
爆炸与地图已经完成
